version: 0.3.{build}
image:
- Visual Studio 2019
- Ubuntu
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_build:
- cmd: dotnet restore
- sh: dotnet restore
build:
  project: Cemiyet.sln
  parallel: true
  verbosity: minimal
test_script:
- cmd: >-
    dotnet test
- sh: >-
    dotnet test
