version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: cemiyet
      POSTGRES_PASSWORD: cemiyet
      POSTGRES_DB: cemiyet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # redis:
  #   image: redis:7
  #   ports:
  #     - "6379:6379"
  #
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672" # management UI
  #
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
  #   environment:
  #     - discovery.type=single-node
  #     - ES_JAVA_OPTS=-Xms1g -Xmx1g
  #   ports:
  #     - "9200:9200"

volumes:
  postgres_data:
