<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Cemiyet.Modules.Identity.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\SharedKernel\Infrastructure\Cemiyet.SharedKernel.Infrastructure.csproj" />
    <ProjectReference Include="..\Domain\Cemiyet.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="..\Application\Cemiyet.Modules.Identity.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
  </ItemGroup>
</Project>
