// <auto-generated />
using System;
using Cemiyet.Persistence.Application.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Cemiyet.Persistence.Application.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20191109204404_AddedEntityChanges")]
    partial class AddedEntityChanges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Cemiyet.Core.Entities.Dimension", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnName("creation_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnName("creator_id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Height")
                        .HasColumnName("height")
                        .HasColumnType("numeric(4,2)");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnName("modification_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Width")
                        .HasColumnName("width")
                        .HasColumnType("numeric(4,2)");

                    b.HasKey("Id")
                        .HasName("pk_dimensions");

                    b.ToTable("dimensions");
                });

            modelBuilder.Entity("Cemiyet.Core.Entities.EntityChange", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnName("entity_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnName("modification_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModifierId")
                        .HasColumnName("modifier_id")
                        .HasColumnType("uuid");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnName("new_value")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnName("old_value")
                        .HasColumnType("text");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnName("property_name")
                        .HasColumnType("text");

                    b.HasIndex("EntityId")
                        .HasName("ix_entity_changes_entity_id");

                    b.ToTable("entity_changes");
                });

            modelBuilder.Entity("Cemiyet.Core.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnName("creation_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnName("creator_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnName("modification_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id")
                        .HasName("pk_genres");

                    b.ToTable("genres");
                });
#pragma warning restore 612, 618
        }
    }
}
