name: .NET Core CI

on: [push]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-2019]
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with dotnet
      run: |
        dotnet test ./tests/Core.Tests --configuration Release
        dotnet test ./tests/Persistence.Tests --configuration Release
        dotnet test ./tests/Infrastructure.Tests --configuration Release
        dotnet test ./tests/Application.Tests --configuration Release

